version: '3'
services:

  chia:
    image: ghcr.io/chia-network/chia:latest #使用官方镜像
    container_name: chia
    working_dir: /chia-blockchain
    hostname: chia.net
    environment: 
      - plots_dir=/plots
    volumes:
      - ~/.data/chia/plots:/plots
      - ~/.data/chia/.chia:/root/.chia
      - ~/.data/chia/python_keyring/:/root/.local/share/python_keyring/
    # ports:
    #   - 8555:8555
    #   - 8444:8444
    #   - 9256:9256